// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwduuimscoaxgidcipek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3ZHV1aW1zY29heGdpZGNpcGVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NTkxMzMsImV4cCI6MjA3MzEzNTEzM30.nzitF8Oin6rHfOMi00hnWufM4Q4WrFRDTm29RzGNvxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});